#%RAML 1.0
title: Birds API
version: v1
mediaType: application/json
types: !include types/index.raml
resourceTypes:
  hasOptions:
    options:
      displayName: Запросить информацию о ресурсе
      responses:
        200:
          headers:
            Allow:
              example: GET,POST,OPTIONS
/api/v1/birds:
  displayName: Птицы
  type: hasOptions
  post:
    displayName: Добавить список новых птиц
    body: BatchBirdsBuildInfo
    responses: 
      200:
        body: BirdsList
      400:
        description: Некорретные данные запроса
  get:
    displayName: Запросить список птиц
    queryParameters:
      offset?:
        description: Позиция, начиная с которой нужно вернуть птиц
        type: number
        minimum: 0
        default: 0
      limit?:
        description: Максимальное количество птиц, которое нужно вернуть
        type: number
        minimum: 0
        maximum: 1000
        default: 100
      name?:
        description: Название птицы
        type: string
    responses:
      200:
        body: BirdsList
      400:
        description: Некорректные данные запроса
  /{birdId}:
    displayName: Птица
    uriParameters: 
      birdId:
        type: string
        description: Идентификатор птицы
    get:
      displayName: Получить информаицю о птице
      responses: 
        200: 
          body: Bird
        404:
          description: Информация о птице не найдена
/api/v1/files:
  displayName: Файлы
  type: hasOptions
  post:
    body: FileCreationInfo 
    displayName: Загрузить файл на сервер
    responses: 
      200:
        description: Идентификатор созданного файла
        body: FileCreationResultInfo
      400:
        description: Данные запроса некорректны
  /{fileId}:
    displayName: Файл
    uriParameters: 
      fileId:
        type: string
        description: Идентификатор файла
    get: 
      displayName: Получить файл
      responses: 
        200: 
          body: File
        404:
          description: Файл не найден
/api/v1/swagger.json:
  displayName: Описание API по спецификации swagger 2.0
  type: hasOptions
  get:
    displayName: Получить OAS схему API V1
    responses:
      200:
        description: swagger 2.0 документ, описывающий API V1
/api/v1/doc.html:
  displayName: Описание API в html
  type: hasOptions
  get:
    displayName: Получить документация API V1 в html
    responses:
      200:
        description:  Документация API V1 в html
