##Models/Birds
BirdBuildInfo: !include birds/bird-build-info.raml
BirdsList: !include birds/birds-list.raml
Bird: !include birds/bird.raml
BatchBirdsBuildInfo: !include birds/batch-birds-build-info.raml

##Models/Files
FileCreationResultInfo: !include files/file-creation-result-info.raml
FileCreationInfo: !include files/file-creation-info.raml
File: !include files/file.raml
