#%RAML 1.0 DataType
displayName: BirdInfo
description: Информация о птице
type: object
properties: 
  name:
    description: Название птице
    type: string
  description:
    default: Описание птицы
    type: string