#%RAML 1.0 DataType
displayName: BirdInfo
description: Информация о птице
type: object
properties: 
  name:
    description: Название птицы
    type: string
  description:
    description: Описание птицы
    type: string
  imageFileId:
    description: Идентификатор файла с изображением птицы
    type: string
  audioFileId:
    description: Идентификатор файла с записью голоса птицы
    type: string