#%RAML 1.0 DataType
displayName: FileCreationInfo
description: Информация для создания файла
type: object
properties: 
  Name:
    description: Название файла
    type: string
  Data:
    description: Бинарные данные
    type: array
